
networks:
  mojaloop-net:
    name: mojaloop-net


services:
  national-bank-sandbox-mock:
    image: stoplight/prism:4
    networks:
      - mojaloop-net
    command: mock -h 0.0.0.0 -p 5010 "/tmp/nat-bank-api-spec.yml"
    volumes:
      - ./src/api-spec:/tmp
    ports:
      - "5010:5010"
    init: true
    container_name: nat-bank-sandbox-mock
    restart: unless-stopped




  